name: "todo-mitsukeru-kun"
description: "Compile a list of TODO comments for each file into an issue."
runs:
  using: "composite"
  steps:
    - run:  ${{ github.action_path }}/src/todo-mitsukeru-kun
      shell: bash
branding:
    color: "blue"
    icon: "check-square"
